import { useEffect, useMemo, useRef, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Search, RefreshCw, SlidersHorizontal } from "lucide-react";
import { PageHeader } from "@/components/layout/PageHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { useAppStore } from "@/lib/store";
import { getDiscoveryCatalog, getDiscoveryCandidates, getDiscoveryEvidence, getDiscoveryUniversePreview } from "@/lib/bollinger-discovery-fns";
import { DISCOVERY_DEFAULTS, discoveryConfigFromVersion, sanitizeDiscoveryConfig, STRATEGIES, type Strategy, type DiscoveryConfig } from "@/lib/bollinger/discovery";
import { UNIVERSE_KINDS, validTopOptions, type UniverseKind, type TopChoice } from "@/lib/bollinger/discovery-universe";
import type { StoredCandidate } from "@/server/bollinger-discovery-store";
import { BollingerManualDiagnostic } from "@/components/charts/BollingerManualDiagnostic";
import { activeBollingerLedgers, evaluateDiscoveryAlerts, loadBollingerLedger, saveBollingerLedger } from "@/lib/bollinger/alerts";
import { notifyAlert } from "@/lib/wire/use-live-wire";

export const Route=createFileRoute("/bollinger")({component:BollingerDiscoveryPage,head:()=>({meta:[{title:"Bollinger Screener 2.0 · Long Pre-Breakout"}]})});
const LABELS:Record<Strategy,string>={"long-pre-breakout":"Long Pre-Breakout","squeeze-watch":"Squeeze Watch",triggered:"Triggered","follow-through":"Follow-Through","failed-breakout":"Failed Breakout",pullback:"Pullback","mean-reversion-watch":"Mean Reversion","bear-breakdown":"Bear / Breakdown"};
const STATUS:Record<string,string>={DATABASE_MISSING:"공유 DB 미설정 · 기존 Neon 연결이 필요합니다.",MIGRATION_0005_REQUIRED:"스크리너 저장 테이블 미적용 · migration 0005가 필요합니다.",UNIVERSE_MISSING:"편입 목록 미확보 · 수집기에 유니버스 등록이 필요합니다.",DATABASE_QUERY_FAILED:"저장 자료 조회 실패 · DB 연결과 실행 기록을 확인하세요."};
const format=(v:number|null|undefined,d=1)=>v==null||!Number.isFinite(v)?"—":v.toLocaleString("ko-KR",{maximumFractionDigits:d});
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const componentNames:Record<string,string>={market:"시장",sector:"섹터",trend:"롱 추세",compression:"변동성 압축",position:"돌파 전 위치",momentum:"모멘텀",relativeStrength:"시장 대비 RS",dryUp:"거래량 건조"};
function ChartLink({row}:{row:StoredCandidate}) {
  return <Link className="font-semibold text-desk-teal hover:underline" to="/chart" search={{symbols:`${row.market}:${row.symbol}`,layout:"1",interval:"day",range:"2y",discoveryUniverse:row.universeId,discoveryVersion:row.configVersion}}>{row.name}</Link>;
}
function Explanation({row,onClose}:{row:StoredCandidate|null;onClose:()=>void}) {
  return <Sheet open={!!row} onOpenChange={v=>{if(!v)onClose();}}><SheetContent className="overflow-y-auto"><SheetHeader><SheetTitle>{row?.name} · 선정 근거</SheetTitle><SheetDescription>{row?.symbol} · {row?.date} · 완료 일봉</SheetDescription></SheetHeader>{row&&<div className="space-y-4 text-sm">
    <div className="rounded-lg bg-muted p-3"><p className="font-medium">{row.state} · Long Readiness {format(row.score.value)}</p><p className="mt-2 text-xs text-muted-foreground">Coverage {format(row.score.coverage*100,0)}%. 점수는 수익 확률이 아닙니다.</p></div>
    {Object.entries(row.score.components).map(([key,c])=><section key={key} className="border-b border-border pb-3"><div className="flex justify-between gap-2 font-medium"><span>{componentNames[key]??key}</span><span>{format(c.score)} / {c.max}</span></div><p className="mt-1 text-xs text-muted-foreground">{c.reason} · {c.availability}</p><dl className="mt-2 grid grid-cols-2 gap-2 text-xs">{Object.entries(c.inputs).map(([k,v])=><div className="min-w-0 break-words" key={k}><dt className="text-muted-foreground">{k}</dt><dd>{typeof v==="number"?format(v,3):v==null?"미확보":String(v)}</dd></div>)}</dl></section>)}
    <section><h3 className="font-medium">저항과 돌파</h3><p className="mt-2">저항 {format(row.resistance)} · {row.resistanceMethod}</p><p className="mt-1">돌파 {row.trigger?.date??"미확인"} · 고정 저항 {format(row.trigger?.resistance)} · 확인 점수 {format(row.confirmationScore)}</p><p className="mt-1">사전 압축 {format(row.trigger?.priorCompression)} · 사전 Long Readiness {format(row.trigger?.priorArmedScore)}</p></section>
    <ul className="space-y-2 text-xs text-muted-foreground">{[...row.reasons,...row.warnings].map((reason,i)=><li key={i}>{reason}</li>)}</ul><p className="break-words text-xs text-muted-foreground">{row.source} · {row.priceBasis}. 공표 확정·기업행사 처리는 공급자 가용 범위에 따릅니다.</p>
  </div>}</SheetContent></Sheet>;
}
function DiscoveryThresholds({config}:{config:DiscoveryConfig}) {
  const [draft,setDraft]=useState(config);
  const fields:[keyof DiscoveryConfig,string][]=[["squeeze","BBW 최대 분위수"],["percentBMin","%B 최소"],["percentBMax","%B 최대"],["distanceMax","저항 최대 거리 %"],["rsiMin","RSI 최소"],["rsiMax","RSI 최대"],["dryMax","건조 RVOL 최대"],["triggerRvol","돌파 RVOL 최소"],["rsMin","RS 최소 pp"],["minCoverage","최소 Coverage 0–1"],["armedScore","ARMED 최소 점수"]];
  const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(draft,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download="bollinger-thresholds.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <div className="mt-4 space-y-3"><div className="grid gap-3 sm:grid-cols-3 xl:grid-cols-4">{fields.map(([key,label])=><label key={key}>{label}<Input aria-label={label} className="mt-1 min-h-11" type="number" step="any" value={draft[key]} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n))setDraft(sanitizeDiscoveryConfig({...draft,[key]:n}));}}/></label>)}</div><div className="flex flex-wrap gap-4">{([["requireMarket","시장 상승 추세 필수"],["requireSector","섹터 상대 강도 필수"]] as const).map(([key,label])=><label className="flex min-h-11 items-center gap-2" key={key}><input type="checkbox" checked={draft[key]===1} onChange={e=>setDraft(sanitizeDiscoveryConfig({...draft,[key]:e.target.checked?1:0}))}/>{label}</label>)}</div><div className="flex flex-wrap gap-2"><Button variant="outline" className="min-h-11" onClick={download}>설정 JSON 다운로드</Button><Button variant="ghost" className="min-h-11" onClick={()=>setDraft({...DISCOVERY_DEFAULTS})}>권장 계산 기본값</Button></div><p>아래 조정은 저장된 순위를 즉시 다시 계산하지 않습니다. 공개 설정 파일을 수집기의 --config로 계산하고 저장된 계산 버전을 선택하세요.</p></div>;
}
type StudyReport={version:string;researchOnly:boolean;survivorshipBiased?:boolean;options:{start:string;end:string;minimumSamples:number;commissionBps:number;slippageBps:number};groups:{signal:string;horizon:number;split:string;bucket:string;samples:number;reliable:boolean;mean:number|null;median:number|null;winRate:number|null;mfe:number|null;mae:number|null;medianMfe?:number|null;medianMae?:number|null;benchmarkExcess:number|null;sectorExcess?:number|null;universeExcess?:number|null;failedRate?:number|null;failedSamples?:number;followThrough?:Record<string,{samples:number;rate:number|null}>;hits?:Record<string,Record<string,number>>}[];warnings:string[]};
function Evidence({data}:{data:unknown}) {
  const report=data&&typeof data==="object"?data as StudyReport:null;
  const [split,setSplit]=useState("out-of-sample");
  return <section className="rounded-lg border border-border bg-card p-4" aria-label="전략 검증 근거"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">Evidence · 사건 연구</h2><select aria-label="검증 구간" className="min-h-11 rounded border border-input bg-card px-3 text-sm" value={split} onChange={e=>setSplit(e.target.value)}>{["development","validation","out-of-sample"].map(s=><option key={s}>{s}</option>)}</select></div>
    {!report?<p className="mt-3 text-sm text-muted-foreground">저장된 백테스트 결과가 없습니다. 기간·표본·편입 이력을 확보한 후 별도 연구 명령을 실행하세요.</p>:<><p className="mt-3 break-words text-xs text-muted-foreground">{report.options.start} ~ {report.options.end} · {report.version} · 최소 표본 {report.options.minimumSamples} · 비용 편도 {report.options.commissionBps} + 슬리피지 {report.options.slippageBps}bps</p>{report.researchOnly&&<p className="mt-2 font-medium text-desk-orange">{report.survivorshipBiased?"SURVIVORSHIP-BIASED / RESEARCH ONLY":"RESEARCH ONLY · 기업행사·가격 정정 당시 가용성 미검증"}</p>}
      <details className="mt-3 text-xs text-muted-foreground"><summary className="min-h-11 cursor-pointer">위험·조건부 목표 도달·비교 기준</summary>{report.groups.filter(g=>g.split===split&&g.bucket==="all").map(g=><section className="space-y-2 border-t border-border py-3" key={`${g.signal}:${g.horizon}`}><p className="font-medium">{g.signal} · {g.horizon}봉 · n={g.samples} · {g.reliable?"최소 표본 통과":"표본 부족"}</p><p>MFE/MAE 중앙값 {format(g.medianMfe)} / {format(g.medianMae)}% · 실패율 {g.failedRate==null?"—":`${format(g.failedRate*100)}%`} (n={g.failedSamples??0})</p><p>섹터 peer 대비 {format(g.sectorExcess)}pp · 유니버스 가용 peer 평균 대비 {format(g.universeExcess)}pp</p><p>Follow-through {Object.entries(g.followThrough??{}).map(([n,v])=>`${n}봉 ${v.rate==null?"—":`${format(v.rate*100)}%`} (n=${v.samples})`).join(" · ")}</p>{Object.entries(g.hits??{}).map(([rule,count])=><p key={rule}>{rule}% · 목표 먼저 {count["target-first"]??0} · 손절 먼저 {count["stop-first"]??0} · 같은 봉 순서 미상 {count.ambiguous??0} · 미도달 {count.neither??0}</p>)}</section>)}</details>
      <div className="mt-3 overflow-x-auto"><table className="w-full text-xs"><thead><tr>{["신호","봉","표본","평균 / 중앙값","승률","MFE / MAE","시장 대비","근거"].map(t=><th className="px-2 py-3 text-left" key={t}>{t}</th>)}</tr></thead><tbody>{report.groups.filter(g=>g.split===split&&g.bucket==="all").map(g=><tr className="border-t border-border" key={`${g.signal}:${g.horizon}`}><td className="p-2">{g.signal}</td><td className="p-2">{g.horizon}</td><td className="p-2">{g.samples}</td><td className="p-2">{format(g.mean)} / {format(g.median)}%</td><td className="p-2">{g.winRate==null?"—":`${format(g.winRate*100)}%`}</td><td className="p-2">{format(g.mfe)} / {format(g.mae)}%</td><td className="p-2">{format(g.benchmarkExcess)}pp</td><td className="p-2">{g.reliable?"표본 기준 통과":"표본 부족"}</td></tr>)}</tbody></table></div><details className="mt-3 text-xs text-muted-foreground"><summary className="min-h-11 cursor-pointer">점수 구간별 결과와 한계</summary>{report.groups.filter(g=>g.split===split&&g.bucket!=="all"&&g.horizon===20).map(g=><p className="mt-2" key={`${g.signal}:${g.bucket}`}>{g.signal} {g.bucket} · n={g.samples} · 평균 {format(g.mean)}% · {g.reliable?"표본 기준 통과":"표본 부족"}</p>)}{report.warnings.map(w=><p key={w} className="mt-2">{w}</p>)}</details></>}
  </section>;
}
function BollingerDiscoveryPage() {
  const watchlist=useAppStore(s=>s.watchlist),usWatchlist=useAppStore(s=>s.usWatchlist);
  const [strategy,setStrategy]=useState<Strategy>("long-pre-breakout"),[kind,setKind]=useState<UniverseKind>("KOSPI"),[universeId,setUniverseId]=useState("");
  const [top,setTop]=useState<TopChoice>("ALL"),[sector,setSector]=useState(""),[search,setSearch]=useState(""),[minWeight,setMinWeight]=useState(0),[page,setPage]=useState(1),[pageSize,setPageSize]=useState<25|50|100>(50);
  const [minScore,setMinScore]=useState(0),[minCoverage,setMinCoverage]=useState(.8),[sort,setSort]=useState<"score"|"distance"|"rs">("score"),[onlyWatchlist,setOnlyWatchlist]=useState(false),[manual,setManual]=useState(""),[selected,setSelected]=useState<StoredCandidate|null>(null),[advanced,setAdvanced]=useState(false);
  const [sessionAlerts,setSessionAlerts]=useState(false),alertActive=useRef<string|null>(null);
  const catalog=useQuery({queryKey:["bollinger-discovery-catalog"],queryFn:()=>getDiscoveryCatalog(),staleTime:60000});
  const available=useMemo(()=>catalog.data?.universes.filter(u=>u.kind===kind&&(!search||u.label.toLowerCase().includes(search.toLowerCase())))??[],[catalog.data,kind,search]);
  useEffect(()=>{if(!available.some(u=>u.id===universeId))setUniverseId(available[0]?.id??"");},[available,universeId]);
  const universe=catalog.data?.universes.find(u=>u.id===universeId);
  const selection=useMemo(()=>({top,minWeight,sectors:sector?[sector]:[]}),[top,minWeight,sector]);
  const symbols=useMemo(()=>onlyWatchlist?[...watchlist.map(s=>`KR:${s}`),...usWatchlist.map(s=>`US:${s}`)]:manual.trim()?manual.toUpperCase().split(/[\s,;]+/).filter(s=>/^(KR:[0-9A-Z]{6}|US:[A-Z][A-Z0-9.-]{0,14})$/.test(s)):undefined,[onlyWatchlist,watchlist,usWatchlist,manual]);
  const [version,setVersion]=useState<string>(DISCOVERY_DEFAULTS.version);
  const {config,recognized:configRecognized}=discoveryConfigFromVersion(version);
  const query=useQuery({queryKey:["bollinger-discovery",universeId,version,strategy,selection,page,pageSize,minScore,minCoverage,sort,symbols],enabled:!!universeId,queryFn:()=>getDiscoveryCandidates({data:{universeId,configVersion:version,strategy,selection,page,pageSize,minScore,minCoverage,sort,asOf:today(),symbols}}),staleTime:60000});
  const preview=useQuery({queryKey:["bollinger-universe-preview",universeId,selection],enabled:!!universeId,queryFn:()=>getDiscoveryUniversePreview({data:{universeId,selection,page:1}}),staleTime:60000});
  const evidence=useQuery({queryKey:["bollinger-evidence",universeId,version],enabled:!!universeId,queryFn:()=>getDiscoveryEvidence({data:{universeId,version}}),staleTime:60000,refetchInterval:sessionAlerts?60000:false,refetchIntervalInBackground:false});
  useEffect(()=>{
    if(!sessionAlerts||!evidence.data||!universeId){alertActive.current=null;return;}
    const key=`ked:bollinger-discovery-alert:v1:${universeId}:${version}`;
    let storage:Storage|null=null;try{storage=window.localStorage;}catch{/* blocked storage */}
    const events=evidence.data.events.map(e=>e.payload);
    if(alertActive.current!==key){const baseline=evaluateDiscoveryAlerts(events,null,key);baseline.ledger.seen=[...new Set([...baseline.ledger.seen,...(loadBollingerLedger(storage,key)?.seen??[])])].slice(-1000);activeBollingerLedgers.set(key,baseline.ledger);alertActive.current=key;return;}
    const result=evaluateDiscoveryAlerts(events,activeBollingerLedgers.get(key)??null,key);
    activeBollingerLedgers.set(key,result.ledger);saveBollingerLedger(storage,key,result.ledger);
    for(const event of result.fired)notifyAlert(`Bollinger · ${event.type}`,`${event.date} · 일별 수집 감지 · 앱 활성 세션 알림`);
  },[sessionAlerts,evidence.data,universeId,version]);
  useEffect(()=>{setPage(1);setSelected(null);},[universeId,version,strategy,selection,minScore,minCoverage,sort,symbols]);
  const data=query.data,rows=(data?.rows??[]) as StoredCandidate[],counts=Object.fromEntries((data?.counts??[]).map(c=>[c.state,c.count]));
  const reset=()=>{setMinScore(0);setMinCoverage(.8);setSort("score");setTop("ALL");setSector("");setMinWeight(0);setOnlyWatchlist(false);setManual("");setStrategy("long-pre-breakout");setVersion(DISCOVERY_DEFAULTS.version);};
  return <div className="flex min-w-0 flex-col gap-5" data-testid="bollinger-screener"><PageHeader kicker="DAILY DISCOVERY · 2.0" title="Bollinger Screener" lead="상승 추세 안에서 변동성과 거래량이 압축된, 돌파 전 후보를 찾습니다."/>
    <div className="flex flex-wrap items-center justify-between gap-2 text-xs text-muted-foreground"><span>완료 일봉 · BB 20 / 2 · BBW 125 · {version}</span><Button variant="outline" className="min-h-11 gap-2" onClick={()=>{void catalog.refetch();void query.refetch();void evidence.refetch();}}><RefreshCw className="size-4"/>저장 자료 새로고침</Button></div>
    <section className="rounded-lg border border-border bg-card p-4" aria-label="유니버스 구성"><h2 className="flex items-center gap-2 font-semibold"><Search className="size-4"/>Universe</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <label className="text-xs text-muted-foreground">시장 / 편입 기준<select className="mt-1 min-h-11 w-full rounded border border-input bg-card px-3 text-sm text-foreground" value={kind} onChange={e=>{setKind(e.target.value as UniverseKind);setTop("ALL");setSector("");setSearch("");}}>{UNIVERSE_KINDS.filter(k=>!["WATCHLIST","MANUAL"].includes(k)).map(k=><option key={k}>{k}</option>)}</select></label>
      <label className="text-xs text-muted-foreground">{kind==="ETF"?"ETF 이름 / 코드 검색":"저장된 편입 스냅샷"}{kind==="ETF"&&<Input className="mt-1 min-h-11" aria-label="ETF 검색" value={search} onChange={e=>setSearch(e.target.value)} placeholder="KODEX, TIGER, QQQ…"/>}<select aria-label="편입 스냅샷" className="mt-1 min-h-11 w-full rounded border border-input bg-card px-3 text-sm text-foreground" value={universeId} onChange={e=>setUniverseId(e.target.value)}><option value="">편입 이력 미확보</option>{available.map(u=><option key={u.id} value={u.id}>{u.label} · {u.asOf}</option>)}</select></label>
      <label className="text-xs text-muted-foreground">구성 범위<select className="mt-1 min-h-11 w-full rounded border border-input bg-card px-3 text-sm text-foreground" value={top} onChange={e=>setTop(e.target.value==="ALL"?"ALL":Number(e.target.value) as Exclude<TopChoice,"ALL">)}>{validTopOptions(kind).map(n=><option key={n} value={n}>{n==="ALL"?"ALL · 전체 편입":`Top ${n}`}</option>)}</select></label>
      <label className="text-xs text-muted-foreground">섹터<select className="mt-1 min-h-11 w-full rounded border border-input bg-card px-3 text-sm text-foreground" value={sector} onChange={e=>setSector(e.target.value)}><option value="">전체 섹터</option>{universe?.sectors.map(s=><option key={s}>{s}</option>)}</select></label></div>
      <div className="mt-3 flex flex-wrap items-center gap-3 text-sm"><label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={onlyWatchlist} onChange={e=>setOnlyWatchlist(e.target.checked)}/>관심종목 전체와 교집합 ({watchlist.length+usWatchlist.length})</label>{kind==="ETF"&&<label className="flex items-center gap-2">최소 보유비중 %<Input className="min-h-11 w-20" type="number" min={0} max={100} value={minWeight} onChange={e=>setMinWeight(Math.max(0,Math.min(100,Number(e.target.value)||0)))}/></label>}</div>
      {universe&&<p className="mt-2 break-words text-xs text-muted-foreground">편입 기준 {universe.asOf} · 수신 {universe.fetchedAt.slice(0,10)} · {universe.source} · {universe.historical?"당시 가용 편입 이력":"현재 편입 / 과거 연구에는 생존편향"}</p>}
      {preview.data&&"rankingBasis" in preview.data&&<p className="mt-2 text-xs text-muted-foreground">순위 기준 {preview.data.rankingBasis} · 지원 {preview.data.supportedCount} · 제외 {preview.data.excludedCount} · 선택 {preview.data.total}{kind==="ETF"?` · 선택 비중 ${format(preview.data.selectedWeight)}% (재정규화 없음)`:""}</p>}{preview.data?.warnings.map(w=><p className="mt-1 text-xs text-desk-orange" key={w}>{w}</p>)}
      <details className="mt-2 text-xs"><summary className="min-h-11 cursor-pointer text-muted-foreground">편입 미리보기 · 수동 코드 필터</summary><Input className="mb-3 min-h-11" value={manual} onChange={e=>setManual(e.target.value)} placeholder="선택 사항: KR:005930, US:NVDA" aria-label="저장 자료 수동 종목 필터"/><div className="grid gap-2 sm:grid-cols-2">{preview.data?.rows.map(m=><p className="min-w-0 truncate" key={`${m.market}:${m.symbol}`}>{m.name} · {m.symbol} · {m.market} · {m.sector}{kind==="ETF"?` · ${format(m.weight)}%`:""}</p>)}</div>{(preview.data?.total??0)>50&&<p className="mt-2 text-muted-foreground">첫 50개 미리보기입니다. 검색은 전체 선택 범위에 적용됩니다.</p>}</details>
    </section>
    <div className="flex flex-wrap gap-2" role="group" aria-label="전략 선택">{STRATEGIES.map(s=><Button key={s} aria-pressed={strategy===s} variant={strategy===s?"default":"outline"} className="min-h-11" onClick={()=>setStrategy(s)}>{LABELS[s]}</Button>)}</div>
    <section className="grid grid-cols-2 gap-2 sm:grid-cols-4 xl:grid-cols-5" aria-label="후보 파이프라인">{[["선택 범위",data?.requestedCount??0],["가용",data&&"pipeline" in data?data.pipeline?.investible??0:0],["상승 추세",data&&"pipeline" in data?data.pipeline?.bullish??0:0],["압축",data&&"pipeline" in data?data.pipeline?.compressed??0:0],["돌파 전",data&&"pipeline" in data?data.pipeline?.preBreakout??0:0],["ARMED",counts.ARMED??0],["TRIGGERED",counts.TRIGGERED??0],["FOLLOW THROUGH",counts.FOLLOW_THROUGH??0],["FAILED",counts.FAILED??0],["WARMUP",counts.WARMUP??0]].map(([label,count])=><div className="rounded-lg border border-border bg-card p-3" key={label}><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{count}</p></div>)}</section>
    <section className="rounded-lg border border-border bg-card p-4" aria-label="검색 필터"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-sm font-medium">결과 조건</h2><Button className="min-h-11 gap-2" variant="ghost" aria-expanded={advanced} onClick={()=>setAdvanced(!advanced)}><SlidersHorizontal className="size-4"/>고급 기준</Button></div><div className="mt-2 flex flex-wrap items-end gap-3"><label className="text-xs text-muted-foreground">저장된 계산 버전<select className="mt-1 block min-h-11 max-w-xs rounded border border-input bg-card px-3 text-sm text-foreground" value={version} onChange={e=>setVersion(e.target.value)}>{[...new Set([DISCOVERY_DEFAULTS.version,...(catalog.data?.versions??[])])].map(v=><option key={v} value={v}>{v===DISCOVERY_DEFAULTS.version?"기본 · 2.0":v.slice(0,55)}</option>)}</select></label>
      <label className="text-xs text-muted-foreground">Long Readiness ≥<Input className="mt-1 min-h-11 w-24" type="number" min={0} max={100} value={minScore} onChange={e=>setMinScore(Math.max(0,Math.min(100,Number(e.target.value)||0)))}/></label><label className="text-xs text-muted-foreground">Coverage ≥ %<Input className="mt-1 min-h-11 w-24" type="number" min={0} max={100} value={Math.round(minCoverage*100)} onChange={e=>setMinCoverage(Math.max(0,Math.min(100,Number(e.target.value)||0))/100)}/></label><label className="text-xs text-muted-foreground">정렬<select className="mt-1 block min-h-11 rounded border border-input bg-card px-3 text-sm text-foreground" value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="score">Long Readiness</option><option value="distance">저항 거리</option><option value="rs">RS 분위수</option></select></label><Button variant="outline" className="min-h-11" onClick={reset}>기본값 복원</Button></div>
      {advanced&&<div className="mt-4 border-t border-border pt-4 text-xs leading-relaxed text-muted-foreground"><p>{!configRecognized&&"알 수 없는 계산 버전 · 아래 기본 기준은 이 버전의 검증 결과가 아닙니다. "}계산 기준: BB 20 / 2 · BBW 125 · squeeze ≤ {config.squeeze} · 저항 거리 0–{config.distanceMax}% · %B {config.percentBMin}–{config.percentBMax} · RSI {config.rsiMin}–{config.rsiMax} 상승 · RVOL 중앙값 ≤ {config.dryMax} · 돌파 RVOL ≥ {config.triggerRvol} · 실패 1–{config.failedWindow}봉.</p><p className="mt-2">계산 기준은 수집기의 --config와 precompute로 새 버전을 저장합니다. 화면 필터는 저장된 값만 검색합니다. ARMED는 매수 신호가 아니며 점수는 확률이 아닙니다.</p><DiscoveryThresholds key={version} config={config}/></div>}
    </section>
    <div className="flex flex-wrap items-center justify-between gap-2 text-xs text-muted-foreground" aria-live="polite"><span>{query.isFetching?"저장 자료 조회 중…":`${LABELS[strategy]} · ${data?.total??0}개 일치`} · 기본 경로는 DB 조회만 수행</span><label>페이지 크기 <select className="min-h-11 rounded border border-input bg-card px-2" value={pageSize} onChange={e=>{setPageSize(Number(e.target.value) as 25|50|100);setPage(1);}}>{[25,50,100].map(n=><option key={n}>{n}</option>)}</select></label></div>
    {(catalog.data?.status!=="READY"||data&&data.status!=="READY")&&<p role="status" className="rounded-lg border border-border bg-muted p-4 text-sm">{catalog.isError||query.isError?"저장 자료 조회 실패 · 연결을 확인하세요.":STATUS[data?.status??catalog.data?.status??""]??"저장 연결을 확인 중입니다."}</p>}
    {rows.length?<><div className="hidden overflow-x-auto rounded-lg border border-border md:block"><table className="w-full text-xs" aria-label="Long Pre-Breakout 후보"><thead className="bg-muted text-muted-foreground"><tr>{["종목 / 시장 / 섹터","상태","Long Readiness","BBW 분위수","저항 거리","%B / RSI","RVOL / 건조","RS 20 / 63","Coverage","기준일","확인"].map(t=><th className="whitespace-nowrap p-3 text-left font-medium" key={t}>{t}</th>)}</tr></thead><tbody>{rows.map(row=><tr className="border-t border-border" key={`${row.market}:${row.symbol}`}><td className="p-3"><ChartLink row={row}/><p className="mt-1 text-muted-foreground">{row.symbol} · {row.market} · {row.sector}</p></td><td className="p-3">{row.state}</td><td className="p-3 font-semibold">{format(row.score.value)}</td><td className="p-3">{format(row.bbwPercentile)}%</td><td className="p-3">{format(row.distance)}%</td><td className="p-3">{format(row.percentB,2)} / {format(row.rsi)}</td><td className="p-3">{format(row.rvol,2)} / {format(row.dryRvol,2)}×</td><td className="p-3">{format(row.rs20)} / {format(row.rs63)}pp</td><td className="p-3">{format(row.score.coverage*100,0)}%</td><td className="whitespace-nowrap p-3">{row.date}</td><td className="p-3"><Button variant="ghost" className="min-h-11" onClick={()=>setSelected(row)}>근거</Button></td></tr>)}</tbody></table></div>
      <div className="grid gap-3 md:hidden">{rows.map(row=><article className="rounded-lg border border-border bg-card p-4" key={`${row.market}:${row.symbol}`}><div className="flex justify-between gap-2"><ChartLink row={row}/><span className="text-xs text-desk-teal">{row.state}</span></div><p className="mt-1 text-xs text-muted-foreground">{row.symbol} · {row.market} · {row.sector}</p><dl className="mt-4 grid grid-cols-3 gap-3 text-sm">{[["Readiness",format(row.score.value)],["저항 거리",`${format(row.distance)}%`],["BBW 분위수",`${format(row.bbwPercentile)}%`],["RS 63",`${format(row.rs63)}pp`],["건조 RVOL",`${format(row.dryRvol,2)}×`],["Coverage",`${format(row.score.coverage*100,0)}%`]].map(([t,v])=><div key={t}><dt className="text-xs text-muted-foreground">{t}</dt><dd className="mt-1 font-medium">{v}</dd></div>)}</dl><div className="mt-4 flex items-center justify-between gap-2"><p className="text-xs text-muted-foreground">{row.date}</p><Button className="min-h-11" variant="outline" onClick={()=>setSelected(row)}>선정 근거</Button></div></article>)}</div></>:<div className="rounded-lg border border-dashed border-border p-8 text-center"><h2 className="text-sm font-medium">{universeId?"조건에 맞는 완료 일봉 후보가 없습니다":"저장된 유니버스가 필요합니다"}</h2><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{universeId?"기준일·Coverage·워밍업과 선택 범위를 확인하세요. 결측과 오래된 값은 최신 순위에서 제외합니다.":"일별 수집기에서 편입 목록과 가격을 저장한 뒤 조회하세요. 화면 조회는 수년 이력을 즉석 다운로드하지 않습니다."}</p></div>}
    <div className="flex items-center justify-end gap-3 text-sm"><Button variant="outline" className="min-h-11" disabled={page<=1} onClick={()=>setPage(page-1)}>이전</Button><span>{page} / {Math.max(1,Math.ceil((data?.total??0)/pageSize))}</span><Button variant="outline" className="min-h-11" disabled={page*pageSize>=(data?.total??0)} onClick={()=>setPage(page+1)}>다음</Button></div>
    {data&&"dates" in data&&<p className="text-xs text-muted-foreground">실제 저장 관측일 {data.dates?.first??"미확보"} ~ {data.dates?.last??"미확보"}. 최근 기준은 4달력일이며 휴장일을 임의로 확정하지 않습니다.</p>}<Evidence data={evidence.data?.evidence}/><details className="rounded-lg border border-border bg-card p-4 text-sm"><summary className="min-h-11 cursor-pointer font-medium">Signal monitoring · 감지와 알림 전송</summary><label className="flex min-h-11 items-center gap-2 text-xs"><input type="checkbox" checked={sessionAlerts} onChange={e=>setSessionAlerts(e.target.checked)}/>이 브라우저의 활성 세션 알림</label><p className="mt-2 text-xs text-muted-foreground">수집 실행 시 DB에 이벤트를 중복 없이 기록합니다. detected와 알림 전달은 별도입니다. 운영 스케줄러·24시간 감시·메시지 발송은 확인하지 않았습니다.</p>{evidence.data?.events.slice(0,20).map((e,i)=><p className="mt-2 text-xs" key={i}>{String(e.market)}:{String(e.symbol)} · {e.payload.date} · {e.payload.type} · {e.delivery_status}</p>)}</details>
    <details className="rounded-lg border border-border p-4"><summary className="min-h-11 cursor-pointer text-sm font-medium">선택 종목 수동 진단 · 기존 최대 10개 경로</summary><p className="mb-4 text-xs text-muted-foreground">명시적 조회에 한해 기존 시세 경로를 사용합니다. 기본 검색과 별개인 진단입니다.</p><BollingerManualDiagnostic/></details><Explanation row={selected} onClose={()=>setSelected(null)}/>
  </div>;
}
