/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChartRouteImport } from './routes/chart'
import { Route as DisclosuresRouteImport } from './routes/disclosures'
import { Route as EtfsRouteImport } from './routes/etfs'
import { Route as ExportDeskRouteImport } from './routes/export-desk'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as RoboticsRouteImport } from './routes/robotics'
import { Route as UsLinkRouteImport } from './routes/us-link'
import { Route as UsResearchRouteImport } from './routes/us-research'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as ApiFeedRouteImport } from './routes/api.feed'
import { Route as ApiMarketStreamRouteImport } from './routes/api.market-stream'
import { Route as ApiWireRouteImport } from './routes/api.wire'
import { Route as EtfsIndexRouteImport } from './routes/etfs.index'
import { Route as EtfsCodeRouteImport } from './routes/etfs.$code'
import { Route as IndustrySectorIdRouteImport } from './routes/industry.$sectorId'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsEtfRouteImport } from './routes/news.etf'
import { Route as NewsKrRouteImport } from './routes/news.kr'
import { Route as NewsUsRouteImport } from './routes/news.us'
import { Route as SettingsAlertsRouteImport } from './routes/settings.alerts'
import { Route as StatusKiwoomRouteImport } from './routes/status.kiwoom'
import { Route as StatusSourcesRouteImport } from './routes/status.sources'
import { Route as StockTickerRouteImport } from './routes/stock.$ticker'
import { Route as UsResearchIndexRouteImport } from './routes/us-research.index'
import { Route as UsResearchReportIdRouteImport } from './routes/us-research.$reportId'
import { Route as UsSymbolRouteImport } from './routes/us.$symbol'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartRoute = ChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosuresRoute = DisclosuresRouteImport.update({
  id: '/disclosures',
  path: '/disclosures',
  getParentRoute: () => rootRouteImport,
} as any)
const EtfsRoute = EtfsRouteImport.update({
  id: '/etfs',
  path: '/etfs',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportDeskRoute = ExportDeskRouteImport.update({
  id: '/export-desk',
  path: '/export-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const RoboticsRoute = RoboticsRouteImport.update({
  id: '/robotics',
  path: '/robotics',
  getParentRoute: () => rootRouteImport,
} as any)
const UsLinkRoute = UsLinkRouteImport.update({
  id: '/us-link',
  path: '/us-link',
  getParentRoute: () => rootRouteImport,
} as any)
const UsResearchRoute = UsResearchRouteImport.update({
  id: '/us-research',
  path: '/us-research',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketStreamRoute = ApiMarketStreamRouteImport.update({
  id: '/api/market-stream',
  path: '/api/market-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWireRoute = ApiWireRouteImport.update({
  id: '/api/wire',
  path: '/api/wire',
  getParentRoute: () => rootRouteImport,
} as any)
const EtfsIndexRoute = EtfsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EtfsRoute,
} as any)
const EtfsCodeRoute = EtfsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => EtfsRoute,
} as any)
const IndustrySectorIdRoute = IndustrySectorIdRouteImport.update({
  id: '/industry/$sectorId',
  path: '/industry/$sectorId',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsEtfRoute = NewsEtfRouteImport.update({
  id: '/news/etf',
  path: '/news/etf',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsKrRoute = NewsKrRouteImport.update({
  id: '/news/kr',
  path: '/news/kr',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsUsRoute = NewsUsRouteImport.update({
  id: '/news/us',
  path: '/news/us',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAlertsRoute = SettingsAlertsRouteImport.update({
  id: '/settings/alerts',
  path: '/settings/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusKiwoomRoute = StatusKiwoomRouteImport.update({
  id: '/status/kiwoom',
  path: '/status/kiwoom',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusSourcesRoute = StatusSourcesRouteImport.update({
  id: '/status/sources',
  path: '/status/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const StockTickerRoute = StockTickerRouteImport.update({
  id: '/stock/$ticker',
  path: '/stock/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const UsResearchIndexRoute = UsResearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsResearchRoute,
} as any)
const UsResearchReportIdRoute = UsResearchReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => UsResearchRoute,
} as any)
const UsSymbolRoute = UsSymbolRouteImport.update({
  id: '/us/$symbol',
  path: '/us/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chart': typeof ChartRoute
  '/disclosures': typeof DisclosuresRoute
  '/etfs': typeof EtfsRouteWithChildren
  '/export-desk': typeof ExportDeskRoute
  '/login': typeof LoginRoute
  '/research': typeof ResearchRoute
  '/robotics': typeof RoboticsRoute
  '/us-link': typeof UsLinkRoute
  '/us-research': typeof UsResearchRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/market-stream': typeof ApiMarketStreamRoute
  '/api/wire': typeof ApiWireRoute
  '/etfs/$code': typeof EtfsCodeRoute
  '/industry/$sectorId': typeof IndustrySectorIdRoute
  '/news/etf': typeof NewsEtfRoute
  '/news/kr': typeof NewsKrRoute
  '/news/us': typeof NewsUsRoute
  '/settings/alerts': typeof SettingsAlertsRoute
  '/status/kiwoom': typeof StatusKiwoomRoute
  '/status/sources': typeof StatusSourcesRoute
  '/stock/$ticker': typeof StockTickerRoute
  '/us-research/$reportId': typeof UsResearchReportIdRoute
  '/us/$symbol': typeof UsSymbolRoute
  '/etfs/': typeof EtfsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/us-research/': typeof UsResearchIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chart': typeof ChartRoute
  '/disclosures': typeof DisclosuresRoute
  '/export-desk': typeof ExportDeskRoute
  '/login': typeof LoginRoute
  '/research': typeof ResearchRoute
  '/robotics': typeof RoboticsRoute
  '/us-link': typeof UsLinkRoute
  '/watchlist': typeof WatchlistRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/market-stream': typeof ApiMarketStreamRoute
  '/api/wire': typeof ApiWireRoute
  '/etfs/$code': typeof EtfsCodeRoute
  '/industry/$sectorId': typeof IndustrySectorIdRoute
  '/news/etf': typeof NewsEtfRoute
  '/news/kr': typeof NewsKrRoute
  '/news/us': typeof NewsUsRoute
  '/settings/alerts': typeof SettingsAlertsRoute
  '/status/kiwoom': typeof StatusKiwoomRoute
  '/status/sources': typeof StatusSourcesRoute
  '/stock/$ticker': typeof StockTickerRoute
  '/us-research/$reportId': typeof UsResearchReportIdRoute
  '/us/$symbol': typeof UsSymbolRoute
  '/etfs': typeof EtfsIndexRoute
  '/news': typeof NewsIndexRoute
  '/us-research': typeof UsResearchIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chart': typeof ChartRoute
  '/disclosures': typeof DisclosuresRoute
  '/etfs': typeof EtfsRouteWithChildren
  '/export-desk': typeof ExportDeskRoute
  '/login': typeof LoginRoute
  '/research': typeof ResearchRoute
  '/robotics': typeof RoboticsRoute
  '/us-link': typeof UsLinkRoute
  '/us-research': typeof UsResearchRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/market-stream': typeof ApiMarketStreamRoute
  '/api/wire': typeof ApiWireRoute
  '/etfs/$code': typeof EtfsCodeRoute
  '/industry/$sectorId': typeof IndustrySectorIdRoute
  '/news/etf': typeof NewsEtfRoute
  '/news/kr': typeof NewsKrRoute
  '/news/us': typeof NewsUsRoute
  '/settings/alerts': typeof SettingsAlertsRoute
  '/status/kiwoom': typeof StatusKiwoomRoute
  '/status/sources': typeof StatusSourcesRoute
  '/stock/$ticker': typeof StockTickerRoute
  '/us-research/$reportId': typeof UsResearchReportIdRoute
  '/us/$symbol': typeof UsSymbolRoute
  '/etfs/': typeof EtfsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/us-research/': typeof UsResearchIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chart'
    | '/disclosures'
    | '/etfs'
    | '/export-desk'
    | '/login'
    | '/research'
    | '/robotics'
    | '/us-link'
    | '/us-research'
    | '/watchlist'
    | '/api/feed'
    | '/api/market-stream'
    | '/api/wire'
    | '/etfs/$code'
    | '/industry/$sectorId'
    | '/news/etf'
    | '/news/kr'
    | '/news/us'
    | '/settings/alerts'
    | '/status/kiwoom'
    | '/status/sources'
    | '/stock/$ticker'
    | '/us-research/$reportId'
    | '/us/$symbol'
    | '/etfs/'
    | '/news/'
    | '/us-research/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chart'
    | '/disclosures'
    | '/export-desk'
    | '/login'
    | '/research'
    | '/robotics'
    | '/us-link'
    | '/watchlist'
    | '/api/feed'
    | '/api/market-stream'
    | '/api/wire'
    | '/etfs/$code'
    | '/industry/$sectorId'
    | '/news/etf'
    | '/news/kr'
    | '/news/us'
    | '/settings/alerts'
    | '/status/kiwoom'
    | '/status/sources'
    | '/stock/$ticker'
    | '/us-research/$reportId'
    | '/us/$symbol'
    | '/etfs'
    | '/news'
    | '/us-research'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/chart'
    | '/disclosures'
    | '/etfs'
    | '/export-desk'
    | '/login'
    | '/research'
    | '/robotics'
    | '/us-link'
    | '/us-research'
    | '/watchlist'
    | '/api/feed'
    | '/api/market-stream'
    | '/api/wire'
    | '/etfs/$code'
    | '/industry/$sectorId'
    | '/news/etf'
    | '/news/kr'
    | '/news/us'
    | '/settings/alerts'
    | '/status/kiwoom'
    | '/status/sources'
    | '/stock/$ticker'
    | '/us-research/$reportId'
    | '/us/$symbol'
    | '/etfs/'
    | '/news/'
    | '/us-research/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChartRoute: typeof ChartRoute
  DisclosuresRoute: typeof DisclosuresRoute
  EtfsRoute: typeof EtfsRouteWithChildren
  ExportDeskRoute: typeof ExportDeskRoute
  LoginRoute: typeof LoginRoute
  ResearchRoute: typeof ResearchRoute
  RoboticsRoute: typeof RoboticsRoute
  UsLinkRoute: typeof UsLinkRoute
  UsResearchRoute: typeof UsResearchRouteWithChildren
  WatchlistRoute: typeof WatchlistRoute
  ApiFeedRoute: typeof ApiFeedRoute
  ApiMarketStreamRoute: typeof ApiMarketStreamRoute
  ApiWireRoute: typeof ApiWireRoute
  IndustrySectorIdRoute: typeof IndustrySectorIdRoute
  NewsEtfRoute: typeof NewsEtfRoute
  NewsKrRoute: typeof NewsKrRoute
  NewsUsRoute: typeof NewsUsRoute
  SettingsAlertsRoute: typeof SettingsAlertsRoute
  StatusKiwoomRoute: typeof StatusKiwoomRoute
  StatusSourcesRoute: typeof StatusSourcesRoute
  StockTickerRoute: typeof StockTickerRoute
  UsSymbolRoute: typeof UsSymbolRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart': {
      id: '/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosures': {
      id: '/disclosures'
      path: '/disclosures'
      fullPath: '/disclosures'
      preLoaderRoute: typeof DisclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etfs': {
      id: '/etfs'
      path: '/etfs'
      fullPath: '/etfs'
      preLoaderRoute: typeof EtfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-desk': {
      id: '/export-desk'
      path: '/export-desk'
      fullPath: '/export-desk'
      preLoaderRoute: typeof ExportDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robotics': {
      id: '/robotics'
      path: '/robotics'
      fullPath: '/robotics'
      preLoaderRoute: typeof RoboticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/us-link': {
      id: '/us-link'
      path: '/us-link'
      fullPath: '/us-link'
      preLoaderRoute: typeof UsLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/us-research': {
      id: '/us-research'
      path: '/us-research'
      fullPath: '/us-research'
      preLoaderRoute: typeof UsResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market-stream': {
      id: '/api/market-stream'
      path: '/api/market-stream'
      fullPath: '/api/market-stream'
      preLoaderRoute: typeof ApiMarketStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wire': {
      id: '/api/wire'
      path: '/api/wire'
      fullPath: '/api/wire'
      preLoaderRoute: typeof ApiWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etfs/': {
      id: '/etfs/'
      path: '/'
      fullPath: '/etfs/'
      preLoaderRoute: typeof EtfsIndexRouteImport
      parentRoute: typeof EtfsRoute
    }
    '/etfs/$code': {
      id: '/etfs/$code'
      path: '/$code'
      fullPath: '/etfs/$code'
      preLoaderRoute: typeof EtfsCodeRouteImport
      parentRoute: typeof EtfsRoute
    }
    '/industry/$sectorId': {
      id: '/industry/$sectorId'
      path: '/industry/$sectorId'
      fullPath: '/industry/$sectorId'
      preLoaderRoute: typeof IndustrySectorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/etf': {
      id: '/news/etf'
      path: '/news/etf'
      fullPath: '/news/etf'
      preLoaderRoute: typeof NewsEtfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/kr': {
      id: '/news/kr'
      path: '/news/kr'
      fullPath: '/news/kr'
      preLoaderRoute: typeof NewsKrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/us': {
      id: '/news/us'
      path: '/news/us'
      fullPath: '/news/us'
      preLoaderRoute: typeof NewsUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/alerts': {
      id: '/settings/alerts'
      path: '/settings/alerts'
      fullPath: '/settings/alerts'
      preLoaderRoute: typeof SettingsAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/kiwoom': {
      id: '/status/kiwoom'
      path: '/status/kiwoom'
      fullPath: '/status/kiwoom'
      preLoaderRoute: typeof StatusKiwoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/sources': {
      id: '/status/sources'
      path: '/status/sources'
      fullPath: '/status/sources'
      preLoaderRoute: typeof StatusSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$ticker': {
      id: '/stock/$ticker'
      path: '/stock/$ticker'
      fullPath: '/stock/$ticker'
      preLoaderRoute: typeof StockTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/us-research/': {
      id: '/us-research/'
      path: '/'
      fullPath: '/us-research/'
      preLoaderRoute: typeof UsResearchIndexRouteImport
      parentRoute: typeof UsResearchRoute
    }
    '/us-research/$reportId': {
      id: '/us-research/$reportId'
      path: '/$reportId'
      fullPath: '/us-research/$reportId'
      preLoaderRoute: typeof UsResearchReportIdRouteImport
      parentRoute: typeof UsResearchRoute
    }
    '/us/$symbol': {
      id: '/us/$symbol'
      path: '/us/$symbol'
      fullPath: '/us/$symbol'
      preLoaderRoute: typeof UsSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EtfsRouteChildren {
  EtfsCodeRoute: typeof EtfsCodeRoute
  EtfsIndexRoute: typeof EtfsIndexRoute
}

const EtfsRouteChildren: EtfsRouteChildren = {
  EtfsCodeRoute: EtfsCodeRoute,
  EtfsIndexRoute: EtfsIndexRoute,
}

const EtfsRouteWithChildren = EtfsRoute._addFileChildren(EtfsRouteChildren)

interface UsResearchRouteChildren {
  UsResearchReportIdRoute: typeof UsResearchReportIdRoute
  UsResearchIndexRoute: typeof UsResearchIndexRoute
}

const UsResearchRouteChildren: UsResearchRouteChildren = {
  UsResearchReportIdRoute: UsResearchReportIdRoute,
  UsResearchIndexRoute: UsResearchIndexRoute,
}

const UsResearchRouteWithChildren = UsResearchRoute._addFileChildren(
  UsResearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChartRoute: ChartRoute,
  DisclosuresRoute: DisclosuresRoute,
  EtfsRoute: EtfsRouteWithChildren,
  ExportDeskRoute: ExportDeskRoute,
  LoginRoute: LoginRoute,
  ResearchRoute: ResearchRoute,
  RoboticsRoute: RoboticsRoute,
  UsLinkRoute: UsLinkRoute,
  UsResearchRoute: UsResearchRouteWithChildren,
  WatchlistRoute: WatchlistRoute,
  ApiFeedRoute: ApiFeedRoute,
  ApiMarketStreamRoute: ApiMarketStreamRoute,
  ApiWireRoute: ApiWireRoute,
  IndustrySectorIdRoute: IndustrySectorIdRoute,
  NewsEtfRoute: NewsEtfRoute,
  NewsKrRoute: NewsKrRoute,
  NewsUsRoute: NewsUsRoute,
  SettingsAlertsRoute: SettingsAlertsRoute,
  StatusKiwoomRoute: StatusKiwoomRoute,
  StatusSourcesRoute: StatusSourcesRoute,
  StockTickerRoute: StockTickerRoute,
  UsSymbolRoute: UsSymbolRoute,
  NewsIndexRoute: NewsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
